/**
 * Propagate the single source of truth into every derived surface.
 *
 * The tool count and the package version are stated in a dozen files across this
 * repo and the agent plugin. Keeping them in step by hand does not work: the
 * plugin skill sat at 84 tools and the README at 107 while the real count was
 * 112, and nothing failed.
 *
 * Source of truth:
 *   version    -> package.json "version"
 *   toolCount  -> SPEAK_MCP_TOOL_NAMES in src/tool-names.ts, which
 *                 tests/tools-coverage.test.ts already pins to the live registry
 *   categories -> tools.json "categories", regenerated by sync-tools-json.ts
 *
 * Everything else is derived and must never be edited by hand.
 *
 *   npx tsx scripts/sync-plugin.ts           # rewrite derived surfaces
 *   npx tsx scripts/sync-plugin.ts --check   # exit 1 on drift, for CI
 */
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { fileURLToPath } from "url";
import path from "path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const read = (rel: string) => readFileSync(path.join(ROOT, rel), "utf8");

/* ---------------------------------------------------------------- truth --- */

const version: string = JSON.parse(read("package.json")).version;

// Count the entries of SPEAK_MCP_TOOL_NAMES rather than trusting a stored total.
const toolNamesSrc = read("src/tool-names.ts");
const toolCount = (toolNamesSrc.match(/^\s*"[a-z0-9_]+",\s*$/gm) ?? []).length;

const toolsJson = JSON.parse(read("tools.json"));
const categoryCount: number = toolsJson.categories.length;
const toolsJsonTotal: number = toolsJson.totalTools;

if (toolCount === 0) {
  console.error("sync-plugin: could not parse any tool names from src/tool-names.ts");
  process.exit(1);
}

// tools.json is generated from the same registry, so a mismatch means it is
// stale. Fail rather than propagate a number we already know is wrong.
if (toolsJsonTotal !== toolCount) {
  console.error(
    `sync-plugin: tools.json totalTools is ${toolsJsonTotal} but src/tool-names.ts lists ` +
      `${toolCount}. Run "npx tsx scripts/sync-tools-json.ts" first.`,
  );
  process.exit(1);
}

/* --------------------------------------------------------------- rules ---- */

/**
 * The homepage cards group several tools.json categories into one card, so the
 * card counts cannot be read straight off tools.json. The grouping lives here,
 * in one place, keyed by the category id in each card's "View N tools" link.
 *
 * Adding a category to tools.json without listing it here or in
 * NOT_ON_HOMEPAGE fails the check, which forces the decision instead of
 * silently leaving the homepage behind.
 */
const CARD_GROUPS: Record<string, string[]> = {
  media: ["media"],
  "magic-prompt": ["magic-prompt"],
  "search-analytics": ["search-analytics"],
  "folders-views": ["folders-views"],
  "recorders-surveys": ["recorders-surveys"],
  "clips-exports": ["clips", "exports"],
  "meeting-bot": ["meeting-bot"],
  "automations-webhooks": ["automations", "webhooks"],
  "text-fields": ["text-notes", "custom-fields"],
  "embed-other": ["embed-other"],
};

/** Real categories the homepage deliberately does not show a card for. */
const NOT_ON_HOMEPAGE = ["users-team", "dashboards"];

const knownIds: string[] = toolsJson.categories.map((c: { id: string }) => c.id);
const knownTools: string[] = toolsJson.categories.flatMap((c: { tools: { name: string }[] }) =>
  c.tools.map((t) => t.name),
);

const assertCovered = (covered: Set<string>, label: string, hint: string) => {
  const uncovered = knownIds.filter((id) => !covered.has(id));
  if (uncovered.length) {
    console.error(
      `sync-plugin: tools.json categor${uncovered.length === 1 ? "y" : "ies"} ` +
        `${uncovered.map((c) => `"${c}"`).join(", ")} ${label}. ${hint}`,
    );
    process.exit(1);
  }
};

assertCovered(
  new Set([...Object.values(CARD_GROUPS).flat(), ...NOT_ON_HOMEPAGE]),
  "not listed in CARD_GROUPS or NOT_ON_HOMEPAGE in this script",
  "Decide where it belongs on the homepage.",
);

/**
 * README.md documents tools in `<details>` sections whose tables list the tool
 * names, and it does not follow the tools.json category split: it separates
 * search from statistics, for instance. So rather than map display names to
 * category ids, each section's count is taken from its own table, and the union
 * of every section is checked against the registry. That catches a tool the
 * README never documented, which a category-level map would not.
 */
const readmeSections = (text: string) =>
  [...text.matchAll(/<summary>([^(<]+?) \((\d+) tools?\)<\/summary>([\s\S]*?)<\/details>/g)].map(
    (m) => ({
      whole: m[0],
      label: m[1].trim(),
      stated: Number(m[2]),
      tools: [...m[3].matchAll(/^\|\s*`([a-z0-9_]+)`\s*\|/gm)].map((r) => r[1]),
    }),
  );

{
  const documented = new Set(readmeSections(read("README.md")).flatMap((s) => s.tools));
  const undocumented = knownTools.filter((t) => !documented.has(t));
  const unknown = [...documented].filter((t) => !knownTools.includes(t));
  if (undocumented.length || unknown.length) {
    if (undocumented.length) {
      console.error(
        `sync-plugin: README.md documents no row for ${undocumented.length} registered ` +
          `tool(s): ${undocumented.join(", ")}. Add them to the right section.`,
      );
    }
    if (unknown.length) {
      console.error(
        `sync-plugin: README.md documents ${unknown.length} tool(s) that are not ` +
          `registered: ${unknown.join(", ")}. Remove them, or register them.`,
      );
    }
    process.exit(1);
  }
}

const groupTotal = (groupId: string): number =>
  CARD_GROUPS[groupId].reduce((sum, id) => {
    const category = toolsJson.categories.find((c: { id: string }) => c.id === id);
    if (!category) {
      console.error(`sync-plugin: CARD_GROUPS references unknown category "${id}"`);
      process.exit(1);
    }
    return sum + category.tools.length;
  }, 0);

type Rule = { file: string; edit: (text: string) => string };

/** Replace inside a JSON file without reformatting the rest of it. */
const jsonRule = (file: string, edit: (data: any) => void): Rule => ({
  file,
  edit: (text) => {
    const data = JSON.parse(text);
    edit(data);
    return JSON.stringify(data, null, 2) + "\n";
  },
});

const RULES: Rule[] = [
  jsonRule("server.json", (d) => {
    d.version = version;
    for (const pkg of d.packages ?? []) pkg.version = version;
  }),

  jsonRule("plugins/speakai-mcp/plugin.json", (d) => {
    d.version = version;
    d.description = d.description.replace(/\b\d+ MCP tools\b/, `${toolCount} MCP tools`);
  }),

  jsonRule("plugins/speakai-mcp/.claude-plugin/plugin.json", (d) => {
    d.version = version;
  }),

  jsonRule("plugins/speakai-mcp/.codex-plugin/plugin.json", (d) => {
    d.version = version;
  }),

  jsonRule("plugins/speakai-mcp/.mcp.json", (d) => {
    for (const server of Object.values<any>(d.mcpServers ?? {})) {
      server.args = (server.args ?? []).map((a: string) =>
        a.replace(/^@speakai\/mcp-server@[\d.]+$/, `@speakai/mcp-server@${version}`),
      );
    }
  }),

  {
    file: "README.md",
    edit: (t) => {
      let out = t
        .replace(/### MCP Tools \(\d+\)/, `### MCP Tools (${toolCount})`)
        .replace(/\bships \d+ tools\b/, `ships ${toolCount} tools`);

      // Each section states the number of rows in its own table.
      for (const section of readmeSections(out)) {
        const actual = section.tools.length;
        if (actual === section.stated) continue;
        out = out.replace(
          `<summary>${section.label} (${section.stated} tool${section.stated === 1 ? "" : "s"})</summary>`,
          `<summary>${section.label} (${actual} tool${actual === 1 ? "" : "s"})</summary>`,
        );
      }

      return out;
    },
  },

  {
    file: "tools.html",
    edit: (t) =>
      t
        .replace(/\b\d+ tools across \d+ categories\b/g, `${toolCount} tools across ${categoryCount} categories`)
        .replace(/\b\d+ tools\b/g, `${toolCount} tools`),
  },

  jsonRule(".claude-plugin/marketplace.json", (d) => {
    for (const plugin of d.plugins ?? []) {
      if (plugin.version) plugin.version = version;
    }
    if (d.version) d.version = version;
  }),

  {
    file: "llms.txt",
    edit: (t) =>
      t
        .replace(/\bexposes \d+ tools\b/, `exposes ${toolCount} tools`)
        .replace(/\baccess to \d+ tools\b/, `access to ${toolCount} tools`),
  },

  {
    file: "index.html",
    edit: (t) => {
      let out = t
        .replace(
          /<h2>\d+ tools across \d+ categories\.<\/h2>/,
          `<h2>${toolCount} tools across ${categoryCount} categories.</h2>`,
        )
        .replace(/Browse all \d+ tools/, `Browse all ${toolCount} tools`)
        .replace(/<h2>\d+ tools\. Zero memorization\.<\/h2>/, `<h2>${toolCount} tools. Zero memorization.</h2>`);

      // Each capability card is one <article> carrying its category id in the
      // "View N tools in detail" link. Rewrite every count inside that article
      // from tools.json, so a category gaining a tool updates the card too.
      out = out.replace(/<article[\s\S]*?<\/article>/g, (article) => {
        const id = article.match(/href="tools\.html#category-([a-z-]+)"/)?.[1];
        if (!id) return article;
        if (!CARD_GROUPS[id]) {
          console.error(
            `sync-plugin: index.html has a card for "${id}" which is not in CARD_GROUPS. ` +
              `Add it, or fix the link.`,
          );
          process.exit(1);
        }
        return article.replace(/\b\d+ tools\b/g, `${groupTotal(id)} tools`);
      });

      return out;
    },
  },
];

// Every skill that states a total. Per-category counts inside a skill are left
// alone; they describe one category and are checked by check-skill-counts below.
const SKILLS_DIR = "plugins/speakai-mcp/skills";
const skillNames = readdirSync(path.join(ROOT, SKILLS_DIR), { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name);

for (const skill of skillNames) {
  RULES.push({
    file: `${SKILLS_DIR}/${skill}/SKILL.md`,
    edit: (t) =>
      t
        .replace(/\b\d+ MCP tools\b/g, `${toolCount} MCP tools`)
        .replace(/\b\d+ tools across\b/g, `${toolCount} tools across`)
        // The server version in frontmatter metadata, under either key spelling.
        .replace(/^(\s+(?:server-)?version:\s*")[\d.]+(")$/gm, `$1${version}$2`),
  });
}

/* ---------------------------------------------------------------- apply --- */

const drifted: string[] = [];

for (const rule of RULES) {
  let before: string;
  try {
    before = read(rule.file);
  } catch {
    console.error(`sync-plugin: missing derived surface ${rule.file}`);
    process.exit(1);
  }
  const after = rule.edit(before);
  if (after === before) continue;

  drifted.push(rule.file);
  if (!CHECK) writeFileSync(path.join(ROOT, rule.file), after);
}

/* ----------------------------------------------------------------- audit -- */

/**
 * The rules above only fix phrasings someone thought of. This catches the ones
 * nobody did. Any "N tools" that is not a per-category count must equal the
 * total, so a new sentence with a stale number fails instead of shipping.
 *
 * Per-category counts are legitimately different numbers and are excluded by
 * the markup that carries them: `<span class="count">` in index.html and
 * `<summary>` rows in README.md.
 */
const AUDIT_FILES = [
  "README.md",
  "llms.txt",
  "index.html",
  "tools.html",
  "plugins/speakai-mcp/README.md",
  ...skillNames.map((s) => `${SKILLS_DIR}/${s}/SKILL.md`),
];
const stale: string[] = [];

for (const file of AUDIT_FILES) {
  let text: string;
  try {
    text = read(file);
  } catch {
    continue;
  }
  // Per-category counts are legitimately different numbers. In index.html they
  // are rewritten from tools.json by the rule above, so drop those articles
  // before auditing. In README.md they sit in <summary> rows that no rule owns
  // yet, so they are skipped and reported separately by check-category-counts.
  text = text.replace(/<article[\s\S]*?<\/article>/g, "");

  // Skills cite per-category counts as `category-id (N tools)`, and prose wraps,
  // so the pair can straddle a line break. Validate those against the registry
  // over the whole text, then blank them out so the per-line total check below
  // does not mistake a category count for a stale total.
  text = text.replace(/\b([a-z][a-z-]+)\s+\((\d+) tools?\)/g, (whole, id, count) => {
    const category = toolsJson.categories.find((c: { id: string }) => c.id === id);
    if (!category) return whole;
    if (category.tools.length !== Number(count)) {
      stale.push(
        `  ${file}  "${whole.replace(/\s+/g, " ")}" should say ${category.tools.length} tools`,
      );
    }
    return whole.replace(/\S/g, " ");
  });

  text.split("\n").forEach((line, i) => {
    if (line.includes('class="count"') || line.includes("<summary>")) return;
    // "N tools", "N MCP tools" and the singular all state the total.
    for (const m of line.matchAll(/\b(\d+) (?:MCP )?tools?\b/g)) {
      if (Number(m[1]) !== toolCount) {
        stale.push(`  ${file}:${i + 1}  "${m[0]}" should be "${toolCount} tools"`);
      }
    }
  });
}

/**
 * The same trap for versions. Nine files state the package version and the rules
 * above only reach the ones someone remembered, so this catches the rest.
 */
// marketplace.json carries a catalog version of its own, which is not the
// package version, so it is synced but not audited against it.
const VERSION_AUDIT_FILES = [
  "server.json",
  "plugins/speakai-mcp/plugin.json",
  "plugins/speakai-mcp/.claude-plugin/plugin.json",
  "plugins/speakai-mcp/.codex-plugin/plugin.json",
  "plugins/speakai-mcp/.mcp.json",
  ...skillNames.map((s) => `${SKILLS_DIR}/${s}/SKILL.md`),
];

for (const file of VERSION_AUDIT_FILES) {
  let text: string;
  try {
    text = read(file);
  } catch {
    continue;
  }
  text.split("\n").forEach((line, i) => {
    // A semver-shaped token that is not the current version, anywhere these
    // files talk about the server or the package.
    for (const m of line.matchAll(/\b\d+\.\d+\.\d+\b/g)) {
      if (m[0] !== version && !line.includes("schemas/")) {
        stale.push(`  ${file}:${i + 1}  version "${m[0]}" should be "${version}"`);
      }
    }
  });
}

if (stale.length) {
  console.error(
    `sync-plugin: ${stale.length} stale tool count(s) that no rule covers.\n` +
      stale.join("\n") +
      `\n\nAdd a rule for the phrasing, or correct the text by hand.`,
  );
  process.exit(1);
}

if (CHECK) {
  if (drifted.length) {
    console.error(
      `sync-plugin: ${drifted.length} file(s) are out of step with package.json ` +
        `version ${version} and ${toolCount} tools:\n` +
        drifted.map((f) => `  - ${f}`).join("\n") +
        `\n\nRun "npx tsx scripts/sync-plugin.ts" to fix.`,
    );
    process.exit(1);
  }
  console.log(`sync-plugin: all derived surfaces match version ${version} and ${toolCount} tools.`);
} else if (drifted.length) {
  console.log(`sync-plugin: updated ${drifted.length} file(s) to version ${version}, ${toolCount} tools:`);
  for (const f of drifted) console.log(`  - ${f}`);
} else {
  console.log(`sync-plugin: already in step (version ${version}, ${toolCount} tools).`);
}
