/**
 * Propagate the single source of truth into every derived surface.
 *
 * The tool count and the package version are stated in a dozen files across this
 * repo and the agent plugin. Keeping them in step by hand does not work: the
 * plugin skill sat at 84 tools and the README at 107 while the real count was
 * 112, and nothing failed.
 *
 * Source of truth:
 *   version    -> package.json "version"
 *   toolCount  -> SPEAK_MCP_TOOL_NAMES in src/tool-names.ts, which
 *                 tests/tools-coverage.test.ts already pins to the live registry
 *   categories -> tools.json "categories", regenerated by sync-tools-json.ts
 *
 * Everything else is derived and must never be edited by hand.
 *
 *   npx tsx scripts/sync-plugin.ts           # rewrite derived surfaces
 *   npx tsx scripts/sync-plugin.ts --check   # exit 1 on drift, for CI
 */
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import path from "path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const read = (rel: string) => readFileSync(path.join(ROOT, rel), "utf8");

/* ---------------------------------------------------------------- truth --- */

const version: string = JSON.parse(read("package.json")).version;

// Count the entries of SPEAK_MCP_TOOL_NAMES rather than trusting a stored total.
const toolNamesSrc = read("src/tool-names.ts");
const toolCount = (toolNamesSrc.match(/^\s*"[a-z0-9_]+",\s*$/gm) ?? []).length;

const toolsJson = JSON.parse(read("tools.json"));
const categoryCount: number = toolsJson.categories.length;
const toolsJsonTotal: number = toolsJson.totalTools;

if (toolCount === 0) {
  console.error("sync-plugin: could not parse any tool names from src/tool-names.ts");
  process.exit(1);
}

// tools.json is generated from the same registry, so a mismatch means it is
// stale. Fail rather than propagate a number we already know is wrong.
if (toolsJsonTotal !== toolCount) {
  console.error(
    `sync-plugin: tools.json totalTools is ${toolsJsonTotal} but src/tool-names.ts lists ` +
      `${toolCount}. Run "npx tsx scripts/sync-tools-json.ts" first.`,
  );
  process.exit(1);
}

/* --------------------------------------------------------------- rules ---- */

/**
 * The homepage cards group several tools.json categories into one card, so the
 * card counts cannot be read straight off tools.json. The grouping lives here,
 * in one place, keyed by the category id in each card's "View N tools" link.
 *
 * Adding a category to tools.json without listing it here or in
 * NOT_ON_HOMEPAGE fails the check, which forces the decision instead of
 * silently leaving the homepage behind.
 */
const CARD_GROUPS: Record<string, string[]> = {
  media: ["media"],
  "magic-prompt": ["magic-prompt"],
  "search-analytics": ["search-analytics"],
  "folders-views": ["folders-views"],
  "recorders-surveys": ["recorders-surveys"],
  "clips-exports": ["clips", "exports"],
  "meeting-bot": ["meeting-bot"],
  "automations-webhooks": ["automations", "webhooks"],
  "text-fields": ["text-notes", "custom-fields"],
  "embed-other": ["embed-other"],
};

/** Real categories the homepage deliberately does not show a card for. */
const NOT_ON_HOMEPAGE = ["users-team", "dashboards"];

const knownIds: string[] = toolsJson.categories.map((c: { id: string }) => c.id);
const covered = new Set([...Object.values(CARD_GROUPS).flat(), ...NOT_ON_HOMEPAGE]);
const uncovered = knownIds.filter((id) => !covered.has(id));
if (uncovered.length) {
  console.error(
    `sync-plugin: tools.json categor${uncovered.length === 1 ? "y" : "ies"} ` +
      `${uncovered.map((c) => `"${c}"`).join(", ")} not listed in CARD_GROUPS or ` +
      `NOT_ON_HOMEPAGE in this script. Decide where it belongs on the homepage.`,
  );
  process.exit(1);
}

const groupTotal = (groupId: string): number =>
  CARD_GROUPS[groupId].reduce((sum, id) => {
    const category = toolsJson.categories.find((c: { id: string }) => c.id === id);
    if (!category) {
      console.error(`sync-plugin: CARD_GROUPS references unknown category "${id}"`);
      process.exit(1);
    }
    return sum + category.tools.length;
  }, 0);

type Rule = { file: string; edit: (text: string) => string };

/** Replace inside a JSON file without reformatting the rest of it. */
const jsonRule = (file: string, edit: (data: any) => void): Rule => ({
  file,
  edit: (text) => {
    const data = JSON.parse(text);
    edit(data);
    return JSON.stringify(data, null, 2) + "\n";
  },
});

const RULES: Rule[] = [
  jsonRule("server.json", (d) => {
    d.version = version;
    for (const pkg of d.packages ?? []) pkg.version = version;
  }),

  jsonRule("plugins/speakai-mcp/plugin.json", (d) => {
    d.version = version;
    d.description = d.description.replace(/\b\d+ MCP tools\b/, `${toolCount} MCP tools`);
  }),

  jsonRule("plugins/speakai-mcp/.claude-plugin/plugin.json", (d) => {
    d.version = version;
  }),

  jsonRule("plugins/speakai-mcp/.codex-plugin/plugin.json", (d) => {
    d.version = version;
  }),

  jsonRule("plugins/speakai-mcp/.mcp.json", (d) => {
    for (const server of Object.values<any>(d.mcpServers ?? {})) {
      server.args = (server.args ?? []).map((a: string) =>
        a.replace(/^@speakai\/mcp-server@[\d.]+$/, `@speakai/mcp-server@${version}`),
      );
    }
  }),

  {
    file: "README.md",
    edit: (t) =>
      t
        .replace(/### MCP Tools \(\d+\)/, `### MCP Tools (${toolCount})`)
        .replace(/\bships \d+ tools\b/, `ships ${toolCount} tools`),
  },

  {
    file: "llms.txt",
    edit: (t) =>
      t
        .replace(/\bexposes \d+ tools\b/, `exposes ${toolCount} tools`)
        .replace(/\baccess to \d+ tools\b/, `access to ${toolCount} tools`),
  },

  {
    file: "index.html",
    edit: (t) => {
      let out = t
        .replace(
          /<h2>\d+ tools across \d+ categories\.<\/h2>/,
          `<h2>${toolCount} tools across ${categoryCount} categories.</h2>`,
        )
        .replace(/Browse all \d+ tools/, `Browse all ${toolCount} tools`)
        .replace(/<h2>\d+ tools\. Zero memorization\.<\/h2>/, `<h2>${toolCount} tools. Zero memorization.</h2>`);

      // Each capability card is one <article> carrying its category id in the
      // "View N tools in detail" link. Rewrite every count inside that article
      // from tools.json, so a category gaining a tool updates the card too.
      out = out.replace(/<article[\s\S]*?<\/article>/g, (article) => {
        const id = article.match(/href="tools\.html#category-([a-z-]+)"/)?.[1];
        if (!id) return article;
        if (!CARD_GROUPS[id]) {
          console.error(
            `sync-plugin: index.html has a card for "${id}" which is not in CARD_GROUPS. ` +
              `Add it, or fix the link.`,
          );
          process.exit(1);
        }
        return article.replace(/\b\d+ tools\b/g, `${groupTotal(id)} tools`);
      });

      return out;
    },
  },
];

// Every skill that states a total. Per-category counts inside a skill are left
// alone; they describe one category and are checked by check-skill-counts below.
for (const skill of [
  "getting-started",
  "meeting-summaries",
  "research-analysis",
  "clips-and-captions",
  "automations-and-webhooks",
]) {
  RULES.push({
    file: `plugins/speakai-mcp/skills/${skill}/SKILL.md`,
    edit: (t) =>
      t
        .replace(/\b\d+ MCP tools\b/g, `${toolCount} MCP tools`)
        .replace(/\b\d+ tools across\b/g, `${toolCount} tools across`),
  });
}

/* ---------------------------------------------------------------- apply --- */

const drifted: string[] = [];

for (const rule of RULES) {
  let before: string;
  try {
    before = read(rule.file);
  } catch {
    console.error(`sync-plugin: missing derived surface ${rule.file}`);
    process.exit(1);
  }
  const after = rule.edit(before);
  if (after === before) continue;

  drifted.push(rule.file);
  if (!CHECK) writeFileSync(path.join(ROOT, rule.file), after);
}

/* ----------------------------------------------------------------- audit -- */

/**
 * The rules above only fix phrasings someone thought of. This catches the ones
 * nobody did. Any "N tools" that is not a per-category count must equal the
 * total, so a new sentence with a stale number fails instead of shipping.
 *
 * Per-category counts are legitimately different numbers and are excluded by
 * the markup that carries them: `<span class="count">` in index.html and
 * `<summary>` rows in README.md.
 */
const AUDIT_FILES = ["README.md", "llms.txt", "index.html", "plugins/speakai-mcp/README.md"];
const stale: string[] = [];

for (const file of AUDIT_FILES) {
  let text: string;
  try {
    text = read(file);
  } catch {
    continue;
  }
  // Per-category counts are legitimately different numbers. In index.html they
  // are rewritten from tools.json by the rule above, so drop those articles
  // before auditing. In README.md they sit in <summary> rows that no rule owns
  // yet, so they are skipped and reported separately by check-category-counts.
  text = text.replace(/<article[\s\S]*?<\/article>/g, "");

  text.split("\n").forEach((line, i) => {
    if (line.includes('class="count"') || line.includes("<summary>")) return;
    for (const m of line.matchAll(/\b(\d+) tools\b/g)) {
      if (Number(m[1]) !== toolCount) {
        stale.push(`  ${file}:${i + 1}  "${m[0]}" should be "${toolCount} tools"`);
      }
    }
  });
}

if (stale.length) {
  console.error(
    `sync-plugin: ${stale.length} stale tool count(s) that no rule covers.\n` +
      stale.join("\n") +
      `\n\nAdd a rule for the phrasing, or correct the text by hand.`,
  );
  process.exit(1);
}

if (CHECK) {
  if (drifted.length) {
    console.error(
      `sync-plugin: ${drifted.length} file(s) are out of step with package.json ` +
        `version ${version} and ${toolCount} tools:\n` +
        drifted.map((f) => `  - ${f}`).join("\n") +
        `\n\nRun "npx tsx scripts/sync-plugin.ts" to fix.`,
    );
    process.exit(1);
  }
  console.log(`sync-plugin: all derived surfaces match version ${version} and ${toolCount} tools.`);
} else if (drifted.length) {
  console.log(`sync-plugin: updated ${drifted.length} file(s) to version ${version}, ${toolCount} tools:`);
  for (const f of drifted) console.log(`  - ${f}`);
} else {
  console.log(`sync-plugin: already in step (version ${version}, ${toolCount} tools).`);
}
